#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import getpass
import sys
import telnetlib
import os, re

lista = open(b"hosts","r")
user = input("Enter your telnet username : ")
password = getpass.getpass()
for item in lista:
    h = item.split()
    HOST = h[0]
    tn = telnetlib.Telnet(HOST)
    tn.read_until(b"Username: ")
    tn.write(user.encode('ascii') + b"\n")
    if password:
        tn.read_until(b"Password: ")
        tn.write(password.encode('ascii') + b"\n")
    tn.write(b"enable\n")
    tn.write(password.encode('ascii') + b"\n")
    tn.write(b"show cdp neighbors\n")
    tn.write(b"end\n")
    tn.write(b"exit\n")
    with open('vizinhos.txt', 'a') as arquivo:
        arquivo.write(str(tn.read_all()))
lista.close()
with open("vizinhos.txt", "r") as myfile:
    dado = myfile.read()
    lista = dado.split()
    for l in lista:
        if re.search("show", l):
            print("Hostname eh: ", l[4:-5])
        if not (re.search("#",l) or re.search("enable",l)) and re.search("nR", l):
            print("Nome do vizinho: ",l[-3::])
        #print(l) 
