#!/usr/bin/python
# -*- coding: UTF-8 -*-

#teste
#import tkinter as tk
from tkinter import messagebox
import urllib.request
import os, re
import time
from datetime import datetime

print("Testando conexão...")
now = datetime.now()
tempo = now.strftime("%d/%m/%Y, %H:%M:%S")
net = "xxx.xxx.xxx.xxx"
mpls = "xxx.xxx.xxx.xxx"
cmd = "ping " + net
cmd2 = "ping " + mpls
r = "".join(os.popen(cmd).readlines())
s = "".join(os.popen(cmd2).readlines())
try:
    t = urllib.request.urlopen("http://www.google.com").getcode()
    if t == 200:
        INTERNET = "INTERNET OK! "
        messagebox.showinfo("Conectividade", INTERNET)
except:
    INTERNET = "INTERNET NÃO OK! "
    messagebox.showerror("Conectividade", INTERNET)
if re.search("Recebidos = 4", s):
    MPLS = "REDE MPLS OK! "
    messagebox.showinfo("Conectividade", MPLS)
else:
    MPLS = "REDE MPLS NÃO OK! " 
    messagebox.showerror("Conectividade", MPLS)
if re.search("Recebidos = 4", r):
    REDE_LOCAL = "REDE LOCAL OK! "
    messagebox.showinfo("Conectividade", REDE_LOCAL )
else:
    REDE_LOCAL = "REDE LOCAL NÃO OK! "
    messagebox.showerror("Conectividade", REDE_LOCAL)
with open('conectividade.txt', 'a') as arquivo:
    arquivo.write(str(INTERNET))
    arquivo.write(str(tempo))
    arquivo.write("\n")
    arquivo.write(str(REDE_LOCAL))
    arquivo.write(str(tempo))
    arquivo.write("\n")
    arquivo.write(str(MPLS))
    arquivo.write(str(tempo))
    arquivo.write("\n")
    arquivo.close()
del INTERNET
del REDE_LOCAL
del MPLS
