#!/usr/bin/python
# -*- coding: UTF-8 -*-

import os, re
print("Verificando conexao...")
for ping in range(1,254):
    address = "192.168.1." + str(ping)
    file = open('ping.txt', 'a')
    cmd = "ping -c1 " + address
    r = "".join(os.popen(cmd).readlines())
    file.write(r)
    file.close()
with open("ping.txt", "r") as myfile:
    data = myfile.readlines()
    for d in data:
        if re.search("ping statistics", d):
            print(d)
        elif re.search("packets transmitted", d):
            print(d)
        elif re.search("min/avg/max/mdev", d):
            print(d)
